title:       "Operating Systems 2021-1 (OS211)"
version:     "001--03/03/2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Muhammad Fathan Muthahhari"
address:          "Bogor"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://zsaschz.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/Zsaschz/os211"
urlghpage:        "https://zsaschz.github.io/os211/"